### ISSUE TITLE
How can display Text and qrcode on LCD display in sunmi T2mini? Can you demo example?

### ISSUE THREAD

**Issue by toulao** [laiiihz/sunmi_printer_service#1]

**Comment by laiiihz** [comment]
https://github.com/laiiihz/sunmi_printer_service/blob/Main/example/lib/main.dart
this is a simple print demo, do you mean the printing function？
this project only support printing text
qrcode will add in future release

**Comment by toulao** [comment]
Thank you. I want to cut paper, but it not cut. how can fix?

**Comment by laiiihz** [comment]
![image](https://user-images.githubusercontent.com/35956195/137886778-ec573333-7382-4716-b5e1-27d427211ed5.png)

I will add this feature tomorrow or welcome pr

**Comment by laiiihz** [comment]
checkout the main branch version

```yaml
  sunmi_printer_service:
    git: 
      url: https://github.com/laiiihz/sunmi_printer_service
```

not fully tested as there is no related device
